export const charactersData = [
  {
    id: 1,
    name: 'ZOE',
    modeling: 'APPROVED',
    surfacing: 'APPROVED',
    rigging: 'APPROVED',
    artist: 'Sophia/surfacing',
    notes: 'Need to check in lighting environment',
  },
  {
    id: 2,
    name: 'ZOE CONCERT',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'APPROVED',
    artist: 'Sophia/surfacing',
    notes: 'Need to check in lighting environment',
  },
  {
    id: 3,
    name: 'ZOE DEMON',
    modeling: 'APPROVED',
    surfacing: 'APPROVED',
    rigging: 'APPROVED',
    artist: 'Rafi/surfacing',
    notes: 'Need to check in lighting environment',
  },
  {
    id: 4,
    name: 'YASHA',
    modeling: 'APPROVED',
    surfacing: 'APPROVED',
    rigging: 'APPROVED',
    artist: 'Ivan/surfacing',
    notes: 'Done',
  },
  {
    id: 5,
    name: 'DARKO',
    modeling: 'APPROVED',
    surfacing: 'APPROVED',
    rigging: 'APPROVED',
    artist: 'Sophia/surfacing',
    notes: '',
  },
  {
    id: 6,
    name: 'PAGANINI',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'APPROVED',
    artist: 'Sophia/surfacing',
    notes: '',
  },
  {
    id: 7,
    name: 'BARISTA',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'WIP',
    artist: 'Ivan/surfacing',
    notes: 'waiting for face rig',
  },
  {
    id: 8,
    name: 'HORNS LADY',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'WIP',
    artist: 'Ivan/surfacing',
    notes: 'same as above',
  },
  {
    id: 9,
    name: 'MAN IN 1800S',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'NOT STARTED',
    artist: 'Ivan/surfacing',
    notes: '',
  },
  {
    id: 10,
    name: 'WOMAN IN 1800S',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'NOT STARTED',
    artist: 'Ivan/surfacing',
    notes: '',
  },
  {
    id: 11,
    name: 'MAN IN 80S',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'NOT STARTED',
    artist: 'Ivan/surfacing',
    notes: '',
  },
  {
    id: 12,
    name: 'WOMAN IN 80S',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'NOT STARTED',
    artist: 'Ivan/surfacing',
    notes: '',
  },
  {
    id: 13,
    name: 'HORSE',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'NOT STARTED',
    artist: 'Alejandro/surfacing/Roberta Rigging',
    notes: '',
  },
  {
    id: 14,
    name: 'RAVEN',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'WIP',
    artist: 'Alejandro/surfacing/Roberta Rigging',
    notes: '',
  },
];

export const propsData = [
  {
    id: 1,
    name: 'GUITAR + STRAP',
    modeling: 'APPROVED',
    surfacing: 'APPROVED',
    rigging: 'APPROVED',
    artist: 'Alejandro/surfacing',
    notes: 'just waiting on strap fix (adding flower texture to match with yasha\'s suspenders)',
  },
  {
    id: 2,
    name: 'VIOLIN NORMAL',
    modeling: 'APPROVED',
    surfacing: 'APPROVED',
    rigging: 'APPROVED',
    artist: 'Alejandro/surfacing',
    notes: '',
  },
  {
    id: 3,
    name: 'VIOLIN DEMON',
    modeling: 'APPROVED',
    surfacing: 'APPROVED',
    rigging: 'APPROVED',
    artist: 'Alejandro/surfacing',
    notes: '',
  },
  {
    id: 4,
    name: 'METRONOME',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'APPROVED',
    artist: 'Alejandro/surfacing',
    notes: 'needs further cleanup, dust treatment',
  },
  {
    id: 5,
    name: 'PEDAL',
    modeling: 'APPROVED',
    surfacing: 'APPROVED',
    rigging: 'APPROVED',
    artist: '',
    notes: '',
  },
  {
    id: 6,
    name: 'CABLE',
    modeling: 'APPROVED',
    surfacing: 'APPROVED',
    rigging: 'APPROVED',
    artist: '',
    notes: '',
  },
  {
    id: 7,
    name: 'AMP',
    modeling: 'APPROVED',
    surfacing: 'APPROVED',
    rigging: 'APPROVED',
    artist: '',
    notes: '',
  },
  {
    id: 8,
    name: 'SKULL LAMP',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'APPROVED',
    artist: 'Alejandro/surfacing',
    notes: 'need to review in light rig environment',
  },
  {
    id: 9,
    name: 'YASHA\'S MUG',
    modeling: 'APPROVED',
    surfacing: 'NOT STARTED',
    rigging: 'WIP',
    artist: '',
    notes: '',
  },
  {
    id: 10,
    name: 'PAPER CUP',
    modeling: 'APPROVED',
    surfacing: 'NOT STARTED',
    rigging: 'APPROVED',
    artist: 'Alejandro/surfacing',
    notes: '',
  },
  {
    id: 11,
    name: 'HORSE CARRIAGE',
    modeling: 'WIP',
    surfacing: 'NOT STARTED',
    rigging: 'NOT STARTED',
    artist: 'Alejandro/surfacing - Roberta Rig',
    notes: '',
  },
  {
    id: 12,
    name: 'GUITAR GIG BAG',
    modeling: 'APPROVED',
    surfacing: 'NOT STARTED',
    rigging: 'APPROVED',
    artist: 'Alejandro/surfacing',
    notes: '',
  },
  {
    id: 13,
    name: 'TURNTABLE + RECORD',
    modeling: 'APPROVED',
    surfacing: 'NOT STARTED',
    rigging: 'APPROVED',
    artist: '',
    notes: '',
  },
  {
    id: 14,
    name: 'BOOK',
    modeling: 'APPROVED',
    surfacing: 'NOT STARTED',
    rigging: 'APPROVED',
    artist: 'Amit',
    notes: '',
  },
  {
    id: 15,
    name: 'PAPER DRAWING',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'APPROVED',
    artist: 'Amit',
    notes: '',
  },
  {
    id: 16,
    name: 'SHARPIE',
    modeling: 'APPROVED',
    surfacing: 'NOT STARTED',
    rigging: 'APPROVED',
    artist: '',
    notes: '',
  },
  {
    id: 17,
    name: 'RECORD SLEEVE',
    modeling: 'APPROVED',
    surfacing: 'NOT STARTED',
    rigging: 'APPROVED',
    artist: 'Roy/Piero',
    notes: '',
  },
  {
    id: 18,
    name: 'Wall POSTER 1800\'s',
    modeling: 'NOT STARTED',
    surfacing: 'READY TO START',
    rigging: 'NOT STARTED',
    artist: 'Amit/Piero/Roy?',
    notes: '',
  },
  {
    id: 19,
    name: 'VIOLIN CASE',
    modeling: 'NOT STARTED',
    surfacing: 'NOT STARTED',
    rigging: 'NOT STARTED',
    artist: 'Alejandro/surfacing',
    notes: '',
  },
  {
    id: 20,
    name: 'VIOLIN BOW',
    modeling: 'APPROVED',
    surfacing: 'APPROVED',
    rigging: 'APPROVED',
    artist: 'Alejandro/surfacing',
    notes: '',
  },
  {
    id: 21,
    name: 'KETTLE',
    modeling: 'WIP',
    surfacing: 'NOT STARTED',
    rigging: 'NOT STARTED',
    artist: 'Vanessa Model',
    notes: '',
  },
  {
    id: 22,
    name: 'POLAROID',
    modeling: 'APPROVED',
    surfacing: 'READY TO START',
    rigging: 'APPROVED',
    artist: 'Amit/Piero/Roy?',
    notes: 'paintover after 3d pose /Gabi',
  },
  {
    id: 23,
    name: 'FLIER POSTER',
    modeling: 'APPROVED',
    surfacing: 'WIP',
    rigging: 'APPROVED',
    artist: 'Sonia Art',
    notes: 'same rig as paper drawing, different surfacing needed',
  },
];

export const setsData = [
  {
    id: 1,
    name: 'GYM',
    modeling: 'WIP',
    surfacing: 'NOT STARTED',
    rigging: 'NOT STARTED',
    artist: 'Garpi/model, Joel/Surfacing',
    notes: 'do we need the mid stage rigged?',
  },
  {
    id: 2,
    name: 'CEMETARY',
    modeling: 'WIP',
    surfacing: 'NOT STARTED',
    rigging: 'WIP',
    artist: 'Jude/model, Joel/Surfacing',
    notes: 'Temp bars rig needs to be confirmed for final Door/ espresso machin, milk cup to be rigged',
  },
  {
    id: 3,
    name: 'CAFE INT.',
    modeling: 'APPROVED',
    surfacing: 'NOT STARTED',
    rigging: 'WIP',
    artist: 'Vanessa/model, Max/surfacing',
    notes: '',
  },
  {
    id: 4,
    name: 'YASHA\'S STORE',
    modeling: 'WIP',
    surfacing: 'NOT STARTED',
    rigging: 'NOT STARTED',
    artist: 'Vanessa/model',
    notes: 'Kettle/ cups to be rigged',
  },
  {
    id: 5,
    name: 'GENOA EXT.',
    modeling: 'WIP',
    surfacing: 'NOT STARTED',
    rigging: 'NOT STARTED',
    artist: 'Maya/model',
    notes: 'need clothes line and clothes rigged to be animated',
  },
  {
    id: 6,
    name: 'CHURCH INT.',
    modeling: 'READY TO START',
    surfacing: 'NOT STARTED',
    rigging: 'NOT STARTED',
    artist: 'unassigned',
    notes: '',
  },
  {
    id: 7,
    name: 'ZOE\'S ROOM',
    modeling: 'APPROVED',
    surfacing: 'NOT STARTED',
    rigging: 'NOT STARTED',
    artist: 'Maya/model, Max/surfacing',
    notes: '',
  },
  {
    id: 8,
    name: 'HELL TUNNEL',
    modeling: 'READY TO START',
    surfacing: 'NOT STARTED',
    rigging: 'NOT STARTED',
    artist: 'unassigned',
    notes: 'simple environment for generating smoke swirl is sufficient',
  },
];
